[project]
name = "photofinder"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Kyle Sun", email = "interskh@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "boxmot>=25.0.0",
    "httpx",
    "numpy>=2.5.3",
    "open-clip-torch>=3.3.0",
    "pillow>=12.3.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "ultralytics>=8.4.157",
]

[project.scripts]
photofinder = "photofinder.cli:main"

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest",
]
