[project]
name = "photofinder"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Kyle Sun", email = "interskh@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx",
]

[build-system]
requires = ["uv_build>=0.9.27,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest",
]
